### ISSUE TITLE
Submit to Chrome Web Store

### ISSUE THREAD

**Issue by NSExceptional** [kishikawakatsumi/SourceKitForSafari#10]
Loading an unpacked extension is a less-than-ideal way to install them, because it breaks if you move the extension on-disk. Currently, you cannot even install manually packed extensions.

Please submit this to the Chrome Web Store so we can use it on Chrome :)

**Comment by kishikawakatsumi** [comment]
Agreed. It's currently buggy and unstable, so I won't release it at the store right now, but I would like to do so in the near future. Thanks.

**Comment by kishikawakatsumi** [comment]
Submitted Chrome web store.

**Comment by kishikawakatsumi** [comment]
Published https://chrome.google.com/webstore/detail/sourcekit-for-chrome/ndfileljkldjnflefdckeiaedelndafe
