### ISSUE TITLE
Doesn't seem to work for private repos?

### ISSUE THREAD

**Issue by cameroncooke** [kishikawakatsumi/SourceKitForSafari#7]
Haven't been able to get it to work with private repos, checked the `~/Library/Group Containers/27AEDK3C9F.com.kishikawakatsumi.SourceKitForSafari/` path and there is no cloned copy of the private repo. Can't see any logs either, so not sure where to look.

I'm using SSH authentication and `git@git.github.com/repo` URLs when cloning manually.

**Comment by kishikawakatsumi** [comment]
Currently, it does not support private repositories. I have a plan to add support for it. The feature will probably be the one that uses the personal access token.

**Comment by cameroncooke** [comment]
Oh okay, thanks, might be good to put a note in README. Thanks!
